version: "3.7"

# volumes:
#   iset-srv-disk:
#     driver: local
#     driver_opts:
#       type: none
#       device: "./data"
#       o: bind

# networks:
#   iset-srv-network:
#       driver: bridge

services:
  gin:
    container_name: gin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    expose:
      - 8080
    # networks:
    #   - iset-srv-network

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dsoFresherXuanHoa
    ports:
      - "3307:3306"
    expose:
      - 3306
    # networks:
    #   - iset-srv-network
